spring:
 datasource:
   url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true
   username: root
   password: 123456

mybatis:
  type-aliases-package: com.hdu.blog.model
  config-location: classpath:mybatis.xml